### ISSUE TITLE
能否支持在生产环境中, 打印编译信息

### ISSUE THREAD

**Issue by LukerSpringtree** [yjl9903/unplugin-info#372]
### Clear and concise description of the problem

我是从 af探店视频发现这个项目的.

我看了一下readme不确定是否满足我的需求, 想请教一下.

我想在编译完成之后, 在生成环境中, 通过控制台,打印编译信息,
如分支, 时间, 打包人.

这个项目支持吗?

**Comment by yjl9903** [comment]
如果我没有理解错你的意思，当然可以，参考 https://github.com/yjl9903/unplugin-info/blob/main/playground/main.ts

```ts
// main.ts

import time from '~build/time'
import { sha } from '~build/info'

console.log(`Built at: ${time}`)
console.log(`SHA: ${sha}`)
```

`~build/time`, `~build/info`, `~build/package`, `~build/meta` 在构建的时候读取信息，生成一些模块，例如：

```ts
// ~build/info

export const sha = 'xxx'
export const tag = '...'

// ...
```

你可以在你的代码中随意引入这些模块，随意使用它们的值。除了默认提供的 git 相关信息，你可以自己在 `vite.config.ts` 里传入一些其他信息给你的应用，参考 https://github.com/yjl9903/unplugin-info/blob/main/README.md#buildmeta

```ts
// vite.config.ts
export default defineConfig({
  plugins: [
    BuildInfo({
      meta: { message: 'This is set from vite.config.ts' }
    })
  ]
})
```

**Comment by yjl9903** [comment]
> 应该是差不多的, 
> 
> 我这边期待的是,  把要给对象挂载到window下面 . 比如  GLOBAL_INFO
> 
> 需要的时候再打印.
> 
> 
> 
> 而不是上来就打印

你可能需要自己挂一下
