### ISSUE TITLE
Error when use with HtmlWebpackPlugin

### ISSUE THREAD

**Issue by lawvs** [yjl9903/unplugin-info#508]
### Describe the bug

![Screenshot 2024-01-23 at 00 33 57](https://github.com/yjl9903/unplugin-info/assets/18554747/b40da1ab-2cbc-4b6d-a0b9-4ec8a49cbeeb)

### Reproduction

You can check the error from https://github.com/lawvs/profile/pull/42

### Used Package Manager

npm

**Comment by yjl9903** [comment]
It seems to be related with unplugin, is there any issues in the unplugin?

**Comment by yjl9903** [comment]
I added a loadInclude hooks for webpack https://github.com/yjl9903/unplugin-info/commit/5bd3cccaafcb2faff26e6eaf30af162f8d95a274

But I am not sure whether it works for that I am not very familiar with config webpack. Could you make a PR help create a webpack example at `./example/webpack/` ?

**Comment by yjl9903** [comment]
In the webpack example, I think it should work.

I released 0.7.2 just now, and could you check whether it works?

**Comment by lawvs** [comment]
Yes, I believe this issue was fixed at https://github.com/yjl9903/unplugin-info/commit/5bd3cccaafcb2faff26e6eaf30af162f8d95a274. Thank you very much!
