### ISSUE TITLE
BUG: github pages build can not get git info in actions

### ISSUE THREAD

**Issue by yjl9903** [yjl9903/unplugin-info#517]
### Describe the bug

![image](https://github.com/yjl9903/unplugin-info/assets/30072175/be909be4-6cd2-44d1-aebb-be6436ece238)

### Reproduction

https://yjl9903.github.io/unplugin-info/

### Used Package Manager

None

**Comment by lawvs** [comment]
I think the problem is related to https://github.com/rwjblue/git-repo-info/issues/48.

**Comment by yjl9903** [comment]
@lawvs I see ouuan use another package `simple-git`, it seems we can also migrate to use it.

**Comment by lawvs** [comment]
After depending on the git, we can export other useful information like dirty status or a human-readable description by `git describe --always --dirty`.

**Comment by yjl9903** [comment]
> After depending on the git, we can export other useful information like dirty status or a human-readable description by `git describe --always --dirty`.

Yes, we can add API to pass the simple git instance for users to export more information they want.

**Comment by yjl9903** [comment]
Done, https://github.com/yjl9903/unplugin-info?tab=readme-ov-file#buildgit
