### ISSUE TITLE
[docs] typing issue

### ISSUE THREAD

**Issue by ZuBB** [yjl9903/unplugin-info#537]
### Clear and concise description of the problem

I am quite new to the whole Vite ecosystem, so when I googled for build info plugin, your package popped up. 

First of all, the set of features is amazing. Thank you a lot for the efforts you put into it. 

I went with the "Getting started" guide, and it didn't work. Then I did a quick look and found the next line in the examples:
```
"types": ["unplugin-info/client"],
```

maybe this should be explicitly mentioned in docs

**Comment by yjl9903** [comment]
I will move up the typescript section https://github.com/yjl9903/unplugin-info?tab=readme-ov-file#typescript

And there is also plan #522 to generate the type declartion, not use this pre-defined things
