### ISSUE TITLE
When using with latest vite Plugin is missing a setup function

### ISSUE THREAD

**Issue by gaborbernat** [yjl9903/unplugin-info#733]
### Describe the bug

🤔 

### System Info

```Shell
✘ [ERROR] Plugin is missing a setup function [plugin unplugin-info]

    /node_modules/vite/node_modules/esbuild/lib/main.js:1232:14:
      1232 │         throw new Error(`Plugin is missing a setup function`);
           ╵               ^
```

### Used Package Manager

None

**Comment by yjl9903** [comment]
Is there any minimal reproduction?

**Comment by gaborbernat** [comment]
Sadly this is not a public repository so I cannot Share it.

**Comment by yjl9903** [comment]
I saw your log is reported by esbuild.

Which framework / bundler are you using? Directly vite, or other meta framework like nuxt or astro?

And can you check the imported unplugin-info plugin (unplugin-info/vite and so on) matches your bundler?

**Comment by yjl9903** [comment]
> Sadly this is not a public repository so I cannot Share it. 

Not necessary your private repo.

Can you create another minimal example repo that can trigger this error?

**Comment by gaborbernat** [comment]
Directly, and I will try to create a repro...
